EWFS Code Refactor
unitaryfund/wigners_friend pull request #48
Opened 2024-12-29 13:49 UTC by vprusso

This refactor enables better design and structure as well as allowing easier generalizations for qubit register friend
sizes and strategies. Numerous improvements and simplifications made in addition to tests, type-checking, linting, etc.

- [X] Updates to README. Updated usage and examples
- [X] Adding pre-commit hooks for linting, type-checking
- [X] Updated jupyter notebook with refactored approach
- [X] Added `circuit.py` for CNOT (and eventually GHZ)-circuit specific functions
- [X] Added `facets.py` for specifically computing the LF-inequality violations.
- [X] Updates to `plots.py` and `file_io.py` to align with refactored code.
- [X] Added `scenario.py`. This is an abstracted way to generated an EWFS circuit for any charlie/debbie size for any of the ("peek", "reverse_1", "reverse_2") settings and any of the supported strategies ("random", "majority_vote")
- [X] Added unit tests to ensure that the EWFS circuit yields violations for inequalities.
- [X] Added utils to contain some of the general functions for calculating branch factor, decoding results for the majority vote approach, etc.
- [X] Completely generalized experiment and scenario to support arbitrary sizes for both Charlie and Debbie (before Debbie was hard-coded to 1.)
- [X] Added `experiment.py`. This allows one to specify the settings and strategy and compute expectation values.
- [X] Add automated dependabot updates for repository
- [X] Add automated test job for GitHub action
- [X] Add single expectation values
- [X] Add additional tests for EWFS circuit functionality

2025-01-01 21:33 UTC, willzeng requested changes
This is a great update @vprusso. Having the testing set up in particular will be very helpful for the updates going forward that we're working on.

Some minor comments in the review. The major ones are around:
- using Enums for the SETTINGS and STRATEGIES
- dropping the Facets object

Happy to discuss further. Would be good to get this on in quickly so we can work on the pending deprecation of `backend.run` that will happen soon see #49

2025-01-01 21:33 UTC, willzeng commented on ewfs/file_io.py
> +#     return all_results
Should we not just delete this? Any reason to leave it commented out?

2025-01-01 21:33 UTC, willzeng commented on tests/test_experiment.py
> +def test_random_stratgegy(backend, charlie_sizes, debbie_sizes, settings):
```suggestion
def test_random_strategy(backend, charlie_sizes, debbie_sizes, settings):
```

2025-01-01 21:33 UTC, willzeng commented on ewfs/scenario.py
> +STRATEGIES = ["majority_vote", "random"]
While the flexibility of string arguments is tempting, it would be better to have both the SETTINGS and STRATEGIES be defined by ENUMs like in the current main branch, e.g.
```
# Settings for extended Wigner's friend scenario.
class Setting(Enum):
    PEEK = 1
    REVERSE_1 = 2
    REVERSE_2 = 3
```

The advantage here is that (1) when you look at the type of a function that takes a setting you would see that it takes type Setting and can then go to the code where that ENUM is defined to see exactly what options are available and (2) when you have a typo in the string the type checker will get it.

String arguments are tough as users can be lost about what strings they can put in to affect certain behavior.

I'd propose that both SETTINGS and STRATEGIES become enums

2025-01-01 21:33 UTC, willzeng commented on ewfs/scenario.py
> +}
With SETTINGS as an ENUM you then have a dictionary:
```
DEFAULT_ANGLES = {
    PEEK: np.deg2rad(40),
    REVERSE_1: np.deg2rad(230),
    REVERSE_2: np.deg2rad(310),
}
``` 

I'll suppress commenting on other flow down changes from using Enums

2025-01-01 21:33 UTC, willzeng commented on ewfs/scenario.py
> +ALICE, BOB = 0, 1
These should also be an Enum. See comment below about string arguments being replaced with Enums.

2025-01-01 21:33 UTC, willzeng commented on tests/test_experiment.py
> +        shots=10_000,
```suggestion
        shots=1_000,
```
Changing this from 10k to 1k improved test time on my laptop from 15 seconds to under 4 seconds. Is there a reason it needs to be 10k?

2025-01-01 21:33 UTC, willzeng commented on tests/test_experiment.py
> +        shots=10_000,
```suggestion
        shots=1_000,
```

2025-01-01 21:33 UTC, willzeng commented on ewfs/circuit.py
> +        internal_copy: Whether the internal state of the friend's qubits should be copied.
Rather than having `internal_copy` be a flag that branches, it seems that these are two different kinds of CNOT ladders and so should be two different functions: `cnot_ladder` and `internal_cnot_ladder`. This would allow a concise docstring distinction as to the difference.

2025-01-01 21:33 UTC, willzeng commented on ewfs/experiment.py
> +    debbie_sizes: range = range(1, 2),
We should avoid having lists or dicts as defaults in Python as it can lead to unexpected behavior: https://www.pullrequest.com/blog/python-pitfalls-the-perils-of-using-lists-and-dicts-as-default-arguments/#:~:text=However%2C%20the%20problem%20lies%20with,t%20provide%20an%20item%20list.

Can be replaced by setting it to None and then `if None: charlie_sizes = range(1, 3)` in the body of the function.

2025-01-01 21:33 UTC, willzeng commented on ewfs/experiment.py
> +                # Create circuits for each EWFS setting.  Note, we remove barriers in the Qiskit circuit.
```suggestion
                # Create circuits for each EWFS setting.
```
Perhaps this comment is just out of date?

2025-01-01 21:33 UTC, willzeng commented on ewfs/experiment.py
> +                tasks[trial][friend_size] = backend.run(
IBM will be sunsetting backend.run this week! https://docs.quantum.ibm.com/announcements/product-updates/2024-12-17-backend-run

According to the [migration guide](https://docs.quantum.ibm.com/migration-guides/qiskit-runtime), because we are using the probabilities of outcomes we will want to switch to use the `Sampler`.

This should not be fixed in this particular PR and so have recorded it with this issue: #49

2025-01-01 21:33 UTC, willzeng commented on ewfs/experiment.py
> +
Eventually we'll want to move this to a post and pull job model like with metriq-gym. This change will be for a future PR

2025-01-01 21:33 UTC, willzeng commented on ewfs/facets.py
> +        self.strategy = strategy
Should this be an object? It doesn't appear that the state is used much except to decode the results if the majority vote scheme is used. I would be worried about behavior:
```
facet = Facets(..., strategy=MAJORITY_VOTE)
facet.semi_brukner = # wrong answer as decode_results is not called to modify state
facet.compute_violations()
facet.semi_brukner = # right answer
```

To improve this, we can switch this to be more functional. E.g.
```
def semi_brukner(results: dict) -> float:
     ...

def majority_vote(results: dict, charlie_size: int, debbie_size: int) -> dict:
     return decode_results # you can move the logic from decode_results in here

# regular results
semi_brukner(results)
# majority vote results
semi_brukner(majority_vote(results))
```

Then we don't need a Facet object at all. Generally I think it is preferable to avoid having new objects if they aren't ones that a user really needs to learn as a concept.

2025-01-03 13:32 UTC, vprusso commented on ewfs/file_io.py
> +#     return all_results
Yes, we should. Deleted in cba2602.

2025-01-03 13:59 UTC, vprusso commented on ewfs/scenario.py
> +STRATEGIES = ["majority_vote", "random"]
I thought about this, but I am not completely on board with the enum approach. Here are a few reasons why:

1. Deviation from norm
Libraries (like `qiskit`, `scikit-learn`, `numpy`, `pandas`, etc.) use strings for configuration or mode arguments. Strings are intuitive, and users often find it easier to reason about `"peek"` vs. `Setting.PEEK` when reading and writing code.

2. More verbose API

Enums may make simple APIs unnecessarily verbose. For instance:

```py
f("arg")
```

is easier for the user compared to 

```py
from ewfs.scenario import Settings

f(Settings.X.value)
```

3. Imposes tight coupling
Using enums creates a tighter coupling between the module where the enum is defined and every module that references it. 

4. More boilerplate code
Defining low-depth enums for these things imposes more boilerplate in the configuration of the code than just using strings. With enums, every file or function that uses the settings or strategies would need to import the corresponding enum, introducing overhead and potential for circular imports, etc.

There are a few other reasons why I'd prefer to stick with strings over enums, but I think the above makes sense to me. What do you think?

2025-01-03 16:37 UTC, vprusso commented on ewfs/scenario.py
> +STRATEGIES = ["majority_vote", "random"]
Re: From discussion we opted for using enums. The nice thing is that `StrEnum`s do support users supplying either the string value or the enum object. Done in 129b234.

2025-01-03 16:37 UTC, vprusso commented on ewfs/scenario.py
> +}
This and other relevant changes were done in 129b234.

2025-01-03 16:38 UTC, vprusso commented on ewfs/scenario.py
> +ALICE, BOB = 0, 1
Done in 129b234.

2025-01-03 16:38 UTC, vprusso commented on ewfs/experiment.py
> +    debbie_sizes: range = range(1, 2),
Agreed. Changed in 129b234.

2025-01-03 16:38 UTC, vprusso commented on ewfs/experiment.py
> +                tasks[trial][friend_size] = backend.run(
Good point and it's good that we have an issue to track this as well.

2025-01-03 16:41 UTC, vprusso commented on ewfs/experiment.py
> +
True. I've created an issue to track so we don't lose this. 
https://github.com/unitaryfund/wigners_friend/issues/50

2025-01-03 16:41 UTC, vprusso commented on ewfs/facets.py
> +        self.strategy = strategy
This is a very good point. Things are now done in a more functional way in 129b234.

2025-01-03 16:42 UTC, vprusso commented
Thanks @willzeng for the comments. I believe these are now addressed. Let me know if there is anything further!

2025-01-03 18:11 UTC, willzeng commented on ewfs/scenario.py
> +STRATEGIES = ["majority_vote", "random"]
That's a great language feature! Good to know

2025-01-03 18:14 UTC, willzeng approved these changes
LGTM! There are a few other comments here that are outstanding (they were hidden by the compressed thread on github) but that I will make into separate issues.

2025-01-03 18:14 UTC, merged

2025-01-03 18:18 UTC, willzeng commented on tests/test_experiment.py
> +        shots=10_000,
Moved to #54

2025-01-03 18:18 UTC, willzeng commented on tests/test_experiment.py
> +        shots=10_000,
Moved to #54